### PR TITLE
Multi-Root

### PR DESCRIPTION
**Pull request by JaySunSyn**
Merged
https://github.com/Neovici/cosmoz-tree/tree/mat-tests
https://github.com/Neovici/cosmoz-tree/tree/multi-root

And added some fixes & tests.

Please check.

### CODE REVIEW

**Comment by nomego** [comment]
Yes and the same conditions are still present.

The biggest change is that we now support pathLocators that address ancestors that we don't have access to. And then we had a few discussions on other cases with other types of trees for wider support.

A lot of our discussions are spread out in PR 1, but I think the biggest one on the subject is https://github.com/Neovici/cosmoz-tree/pull/1#discussion_r130458582 .

I'm not sure if it's there or somewhere else but we discussed this point and I do agree that for our purposes, we can simplify the logic by saying "it's fine to lack parts of that pathLocator in the beginning, but invalidate any path that can't find a needed path part in the middle or end".
What we're doing now is basically saying "if we can't find _any_ valid path on _any_ node, should we return the best candidate we could find?"
I actually think we shouldn't, just return undefined/null since "best candidate" can be anything, but it's still not right. This would simplify _getPathNodes a bit and enable some performance improvements.

What I'm not sure about though is if I request the pathNodes for 1.2.3.4.5 and only have permission from 3 (recursively), should we return an array with 5 elements, first 2 undefined, or just the last three that we actually had permissions too ?
I would expect to receive as many elements back as I had parts in my pathLocator, but on the other hand that just puts additional error-checking on the caller, likely every time.

Thoughts @plequang @JaySunSyn ?

**Comment by nomego** [comment]
Sorry, yes your implementation also supports missing ancestors but adds a dependency on the "pathLocator" property.

**Comment by plequang** [comment]
> adds a dependency on the "pathLocator" property.
I don't understand. The `getPathNodes` function modified by the PR takes `pathLocator` as an argument.

Also I keep thinking that :
> the function that returns a path should return an array of nodes that start at one of the root, and without any undefined.

If no such path exists, this means you don't have access.

I think you over complicated the test cases in missing ancestor tree tests:
1. The id used as the key for path locator is unique. So id "301" can appear only below only one path.
2. The test for path `1.2.7.8` should return null, as that node does not exists/not visible. There is no point in returning the beginning of the path.

> What I'm not sure about though is if I request the pathNodes for 1.2.3.4.5 and only have permission from 3 (recursively), should we return an array with 5 elements, first 2 undefined

I think it's useless, we won't display anything regarding the 2 undefined nodes. 3 will appear as if it was a root. Think of network shares, or the "shared with me" folder in Google drive.

**Comment by plequang** [comment]
Anyway, I made some tests and this implementation works in real situation scenario.
Will merge it and we can take this discussion later on.

**Pull request merged**
